// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alerts.sql

package storage

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAlerts = `-- name: CountAlerts :one
SELECT count(*) FROM alerts WHERE project_id = $1
`

func (q *Queries) CountAlerts(ctx context.Context, projectID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAlerts, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAlertsByStatus = `-- name: CountAlertsByStatus :one
SELECT count(*) FROM alerts WHERE project_id = $1 AND status = $2
`

type CountAlertsByStatusParams struct {
	ProjectID uuid.UUID   `json:"project_id"`
	Status    AlertStatus `json:"status"`
}

func (q *Queries) CountAlertsByStatus(ctx context.Context, arg CountAlertsByStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAlertsByStatus, arg.ProjectID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAlertByID = `-- name: GetAlertByID :one
SELECT id, project_id, source_type, source_id, title, content, url, matched_keywords, severity, status, created_at, updated_at, tags, classification_reason, monitor_source_id
FROM alerts
WHERE id = $1 AND project_id = $2
`

type GetAlertByIDParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) GetAlertByID(ctx context.Context, arg GetAlertByIDParams) (Alert, error) {
	row := q.db.QueryRow(ctx, getAlertByID, arg.ID, arg.ProjectID)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SourceType,
		&i.SourceID,
		&i.Title,
		&i.Content,
		&i.Url,
		&i.MatchedKeywords,
		&i.Severity,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Tags,
		&i.ClassificationReason,
		&i.MonitorSourceID,
	)
	return i, err
}

const listAlerts = `-- name: ListAlerts :many
SELECT id, project_id, source_type, source_id, title, content, url, matched_keywords, severity, status, created_at, updated_at, tags, classification_reason, monitor_source_id
FROM alerts
WHERE project_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAlertsParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListAlerts(ctx context.Context, arg ListAlertsParams) ([]Alert, error) {
	rows, err := q.db.Query(ctx, listAlerts, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Alert{}
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SourceType,
			&i.SourceID,
			&i.Title,
			&i.Content,
			&i.Url,
			&i.MatchedKeywords,
			&i.Severity,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Tags,
			&i.ClassificationReason,
			&i.MonitorSourceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertsBySourceType = `-- name: ListAlertsBySourceType :many
SELECT id, project_id, source_type, source_id, title, content, url, matched_keywords, severity, status, created_at, updated_at, tags, classification_reason, monitor_source_id
FROM alerts
WHERE project_id = $1 AND source_type = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListAlertsBySourceTypeParams struct {
	ProjectID  uuid.UUID   `json:"project_id"`
	SourceType MonitorType `json:"source_type"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

func (q *Queries) ListAlertsBySourceType(ctx context.Context, arg ListAlertsBySourceTypeParams) ([]Alert, error) {
	rows, err := q.db.Query(ctx, listAlertsBySourceType,
		arg.ProjectID,
		arg.SourceType,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Alert{}
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SourceType,
			&i.SourceID,
			&i.Title,
			&i.Content,
			&i.Url,
			&i.MatchedKeywords,
			&i.Severity,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Tags,
			&i.ClassificationReason,
			&i.MonitorSourceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertsByStatus = `-- name: ListAlertsByStatus :many
SELECT id, project_id, source_type, source_id, title, content, url, matched_keywords, severity, status, created_at, updated_at, tags, classification_reason, monitor_source_id
FROM alerts
WHERE project_id = $1 AND status = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListAlertsByStatusParams struct {
	ProjectID uuid.UUID   `json:"project_id"`
	Status    AlertStatus `json:"status"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListAlertsByStatus(ctx context.Context, arg ListAlertsByStatusParams) ([]Alert, error) {
	rows, err := q.db.Query(ctx, listAlertsByStatus,
		arg.ProjectID,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Alert{}
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SourceType,
			&i.SourceID,
			&i.Title,
			&i.Content,
			&i.Url,
			&i.MatchedKeywords,
			&i.Severity,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Tags,
			&i.ClassificationReason,
			&i.MonitorSourceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAlertStatus = `-- name: UpdateAlertStatus :one
UPDATE alerts
SET status = $3
WHERE id = $1 AND project_id = $2
RETURNING id, project_id, source_type, source_id, title, content, url, matched_keywords, severity, status, created_at, updated_at, tags, classification_reason, monitor_source_id
`

type UpdateAlertStatusParams struct {
	ID        uuid.UUID   `json:"id"`
	ProjectID uuid.UUID   `json:"project_id"`
	Status    AlertStatus `json:"status"`
}

func (q *Queries) UpdateAlertStatus(ctx context.Context, arg UpdateAlertStatusParams) (Alert, error) {
	row := q.db.QueryRow(ctx, updateAlertStatus, arg.ID, arg.ProjectID, arg.Status)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SourceType,
		&i.SourceID,
		&i.Title,
		&i.Content,
		&i.Url,
		&i.MatchedKeywords,
		&i.Severity,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Tags,
		&i.ClassificationReason,
		&i.MonitorSourceID,
	)
	return i, err
}

const upsertAlert = `-- name: UpsertAlert :one
INSERT INTO alerts (project_id, source_type, source_id, title, content, url, matched_keywords, severity, tags, classification_reason, monitor_source_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (project_id, source_type, source_id)
DO UPDATE SET
  title = EXCLUDED.title,
  content = EXCLUDED.content,
  url = EXCLUDED.url,
  matched_keywords = EXCLUDED.matched_keywords,
  tags = EXCLUDED.tags,
  classification_reason = EXCLUDED.classification_reason,
  monitor_source_id = EXCLUDED.monitor_source_id
RETURNING id, project_id, source_type, source_id, title, content, url, matched_keywords, severity, status, created_at, updated_at, tags, classification_reason, monitor_source_id
`

type UpsertAlertParams struct {
	ProjectID            uuid.UUID     `json:"project_id"`
	SourceType           MonitorType   `json:"source_type"`
	SourceID             string        `json:"source_id"`
	Title                string        `json:"title"`
	Content              string        `json:"content"`
	Url                  string        `json:"url"`
	MatchedKeywords      []string      `json:"matched_keywords"`
	Severity             AlertSeverity `json:"severity"`
	Tags                 []string      `json:"tags"`
	ClassificationReason string        `json:"classification_reason"`
	MonitorSourceID      pgtype.UUID   `json:"monitor_source_id"`
}

func (q *Queries) UpsertAlert(ctx context.Context, arg UpsertAlertParams) (Alert, error) {
	row := q.db.QueryRow(ctx, upsertAlert,
		arg.ProjectID,
		arg.SourceType,
		arg.SourceID,
		arg.Title,
		arg.Content,
		arg.Url,
		arg.MatchedKeywords,
		arg.Severity,
		arg.Tags,
		arg.ClassificationReason,
		arg.MonitorSourceID,
	)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SourceType,
		&i.SourceID,
		&i.Title,
		&i.Content,
		&i.Url,
		&i.MatchedKeywords,
		&i.Severity,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Tags,
		&i.ClassificationReason,
		&i.MonitorSourceID,
	)
	return i, err
}
