// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: keywords.sql

package storage

import (
	"context"

	"github.com/google/uuid"
)

const createKeyword = `-- name: CreateKeyword :one
INSERT INTO keywords (project_id, keyword, match_type)
VALUES ($1, $2, $3)
RETURNING id, project_id, keyword, match_type, created_at
`

type CreateKeywordParams struct {
	ProjectID uuid.UUID        `json:"project_id"`
	Keyword   string           `json:"keyword"`
	MatchType KeywordMatchType `json:"match_type"`
}

func (q *Queries) CreateKeyword(ctx context.Context, arg CreateKeywordParams) (Keyword, error) {
	row := q.db.QueryRow(ctx, createKeyword, arg.ProjectID, arg.Keyword, arg.MatchType)
	var i Keyword
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Keyword,
		&i.MatchType,
		&i.CreatedAt,
	)
	return i, err
}

const deleteKeyword = `-- name: DeleteKeyword :exec
DELETE FROM keywords
WHERE id = $1 AND project_id = $2
`

type DeleteKeywordParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) DeleteKeyword(ctx context.Context, arg DeleteKeywordParams) error {
	_, err := q.db.Exec(ctx, deleteKeyword, arg.ID, arg.ProjectID)
	return err
}

const getKeywordByID = `-- name: GetKeywordByID :one
SELECT id, project_id, keyword, match_type, created_at
FROM keywords
WHERE id = $1 AND project_id = $2
`

type GetKeywordByIDParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) GetKeywordByID(ctx context.Context, arg GetKeywordByIDParams) (Keyword, error) {
	row := q.db.QueryRow(ctx, getKeywordByID, arg.ID, arg.ProjectID)
	var i Keyword
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Keyword,
		&i.MatchType,
		&i.CreatedAt,
	)
	return i, err
}

const listKeywords = `-- name: ListKeywords :many
SELECT id, project_id, keyword, match_type, created_at
FROM keywords
WHERE project_id = $1
ORDER BY created_at
`

func (q *Queries) ListKeywords(ctx context.Context, projectID uuid.UUID) ([]Keyword, error) {
	rows, err := q.db.Query(ctx, listKeywords, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Keyword{}
	for rows.Next() {
		var i Keyword
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Keyword,
			&i.MatchType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
