// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package storage

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AlertSeverity string

const (
	AlertSeverityLow      AlertSeverity = "low"
	AlertSeverityMedium   AlertSeverity = "medium"
	AlertSeverityHigh     AlertSeverity = "high"
	AlertSeverityCritical AlertSeverity = "critical"
)

func (e *AlertSeverity) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AlertSeverity(s)
	case string:
		*e = AlertSeverity(s)
	default:
		return fmt.Errorf("unsupported scan type for AlertSeverity: %T", src)
	}
	return nil
}

type NullAlertSeverity struct {
	AlertSeverity AlertSeverity `json:"alert_severity"`
	Valid         bool          `json:"valid"` // Valid is true if AlertSeverity is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAlertSeverity) Scan(value interface{}) error {
	if value == nil {
		ns.AlertSeverity, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AlertSeverity.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAlertSeverity) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AlertSeverity), nil
}

type AlertStatus string

const (
	AlertStatusNew       AlertStatus = "new"
	AlertStatusSeen      AlertStatus = "seen"
	AlertStatusTriaged   AlertStatus = "triaged"
	AlertStatusDismissed AlertStatus = "dismissed"
	AlertStatusResponded AlertStatus = "responded"
)

func (e *AlertStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AlertStatus(s)
	case string:
		*e = AlertStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AlertStatus: %T", src)
	}
	return nil
}

type NullAlertStatus struct {
	AlertStatus AlertStatus `json:"alert_status"`
	Valid       bool        `json:"valid"` // Valid is true if AlertStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAlertStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AlertStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AlertStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAlertStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AlertStatus), nil
}

type KeywordMatchType string

const (
	KeywordMatchTypeExact     KeywordMatchType = "exact"
	KeywordMatchTypeSubstring KeywordMatchType = "substring"
	KeywordMatchTypeRegex     KeywordMatchType = "regex"
)

func (e *KeywordMatchType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = KeywordMatchType(s)
	case string:
		*e = KeywordMatchType(s)
	default:
		return fmt.Errorf("unsupported scan type for KeywordMatchType: %T", src)
	}
	return nil
}

type NullKeywordMatchType struct {
	KeywordMatchType KeywordMatchType `json:"keyword_match_type"`
	Valid            bool             `json:"valid"` // Valid is true if KeywordMatchType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullKeywordMatchType) Scan(value interface{}) error {
	if value == nil {
		ns.KeywordMatchType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.KeywordMatchType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullKeywordMatchType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.KeywordMatchType), nil
}

type MonitorType string

const (
	MonitorTypeReddit MonitorType = "reddit"
	MonitorTypeHn     MonitorType = "hn"
	MonitorTypeWeb    MonitorType = "web"
	MonitorTypeRss    MonitorType = "rss"
	MonitorTypeGithub MonitorType = "github"
)

func (e *MonitorType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MonitorType(s)
	case string:
		*e = MonitorType(s)
	default:
		return fmt.Errorf("unsupported scan type for MonitorType: %T", src)
	}
	return nil
}

type NullMonitorType struct {
	MonitorType MonitorType `json:"monitor_type"`
	Valid       bool        `json:"valid"` // Valid is true if MonitorType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMonitorType) Scan(value interface{}) error {
	if value == nil {
		ns.MonitorType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MonitorType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMonitorType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MonitorType), nil
}

type NotificationDestination string

const (
	NotificationDestinationNtfy    NotificationDestination = "ntfy"
	NotificationDestinationEmail   NotificationDestination = "email"
	NotificationDestinationWebhook NotificationDestination = "webhook"
)

func (e *NotificationDestination) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationDestination(s)
	case string:
		*e = NotificationDestination(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationDestination: %T", src)
	}
	return nil
}

type NullNotificationDestination struct {
	NotificationDestination NotificationDestination `json:"notification_destination"`
	Valid                   bool                    `json:"valid"` // Valid is true if NotificationDestination is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationDestination) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationDestination, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationDestination.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationDestination) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationDestination), nil
}

type NotificationSourceType string

const (
	NotificationSourceTypeReddit NotificationSourceType = "reddit"
	NotificationSourceTypeHn     NotificationSourceType = "hn"
	NotificationSourceTypeWeb    NotificationSourceType = "web"
	NotificationSourceTypeRss    NotificationSourceType = "rss"
	NotificationSourceTypeGithub NotificationSourceType = "github"
	NotificationSourceTypeAll    NotificationSourceType = "all"
)

func (e *NotificationSourceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationSourceType(s)
	case string:
		*e = NotificationSourceType(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationSourceType: %T", src)
	}
	return nil
}

type NullNotificationSourceType struct {
	NotificationSourceType NotificationSourceType `json:"notification_source_type"`
	Valid                  bool                   `json:"valid"` // Valid is true if NotificationSourceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationSourceType) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationSourceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationSourceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationSourceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationSourceType), nil
}

type PostStatus string

const (
	PostStatusDraft      PostStatus = "draft"
	PostStatusScheduled  PostStatus = "scheduled"
	PostStatusPublishing PostStatus = "publishing"
	PostStatusPublished  PostStatus = "published"
	PostStatusFailed     PostStatus = "failed"
)

func (e *PostStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PostStatus(s)
	case string:
		*e = PostStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PostStatus: %T", src)
	}
	return nil
}

type NullPostStatus struct {
	PostStatus PostStatus `json:"post_status"`
	Valid      bool       `json:"valid"` // Valid is true if PostStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPostStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PostStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PostStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPostStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PostStatus), nil
}

type PostType string

const (
	PostTypeText PostType = "text"
	PostTypeLink PostType = "link"
)

func (e *PostType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PostType(s)
	case string:
		*e = PostType(s)
	default:
		return fmt.Errorf("unsupported scan type for PostType: %T", src)
	}
	return nil
}

type NullPostType struct {
	PostType PostType `json:"post_type"`
	Valid    bool     `json:"valid"` // Valid is true if PostType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPostType) Scan(value interface{}) error {
	if value == nil {
		ns.PostType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PostType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPostType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PostType), nil
}

type ProjectRole string

const (
	ProjectRoleOwner  ProjectRole = "owner"
	ProjectRoleAdmin  ProjectRole = "admin"
	ProjectRoleMember ProjectRole = "member"
	ProjectRoleViewer ProjectRole = "viewer"
)

func (e *ProjectRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProjectRole(s)
	case string:
		*e = ProjectRole(s)
	default:
		return fmt.Errorf("unsupported scan type for ProjectRole: %T", src)
	}
	return nil
}

type NullProjectRole struct {
	ProjectRole ProjectRole `json:"project_role"`
	Valid       bool        `json:"valid"` // Valid is true if ProjectRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProjectRole) Scan(value interface{}) error {
	if value == nil {
		ns.ProjectRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProjectRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProjectRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProjectRole), nil
}

type ServiceName string

const (
	ServiceNameNtfy         ServiceName = "ntfy"
	ServiceNameChangedetect ServiceName = "changedetect"
	ServiceNameUmami        ServiceName = "umami"
	ServiceNameRsshub       ServiceName = "rsshub"
)

func (e *ServiceName) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ServiceName(s)
	case string:
		*e = ServiceName(s)
	default:
		return fmt.Errorf("unsupported scan type for ServiceName: %T", src)
	}
	return nil
}

type NullServiceName struct {
	ServiceName ServiceName `json:"service_name"`
	Valid       bool        `json:"valid"` // Valid is true if ServiceName is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullServiceName) Scan(value interface{}) error {
	if value == nil {
		ns.ServiceName, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ServiceName.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullServiceName) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ServiceName), nil
}

type ServiceStatus string

const (
	ServiceStatusProvisioning   ServiceStatus = "provisioning"
	ServiceStatusActive         ServiceStatus = "active"
	ServiceStatusError          ServiceStatus = "error"
	ServiceStatusDeprovisioning ServiceStatus = "deprovisioning"
)

func (e *ServiceStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ServiceStatus(s)
	case string:
		*e = ServiceStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ServiceStatus: %T", src)
	}
	return nil
}

type NullServiceStatus struct {
	ServiceStatus ServiceStatus `json:"service_status"`
	Valid         bool          `json:"valid"` // Valid is true if ServiceStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullServiceStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ServiceStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ServiceStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullServiceStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ServiceStatus), nil
}

type Alert struct {
	ID              uuid.UUID          `json:"id"`
	ProjectID       uuid.UUID          `json:"project_id"`
	SourceType      MonitorType        `json:"source_type"`
	SourceID        string             `json:"source_id"`
	Title           string             `json:"title"`
	Content         string             `json:"content"`
	Url             string             `json:"url"`
	MatchedKeywords []string           `json:"matched_keywords"`
	Severity        AlertSeverity      `json:"severity"`
	Status          AlertStatus        `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type AuditLog struct {
	ID        int64              `json:"id"`
	ProjectID uuid.UUID          `json:"project_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Action    string             `json:"action"`
	Details   []byte             `json:"details"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Keyword struct {
	ID        uuid.UUID          `json:"id"`
	ProjectID uuid.UUID          `json:"project_id"`
	Keyword   string             `json:"keyword"`
	MatchType KeywordMatchType   `json:"match_type"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type MonitorSource struct {
	ID        uuid.UUID          `json:"id"`
	ProjectID uuid.UUID          `json:"project_id"`
	Type      MonitorType        `json:"type"`
	Config    []byte             `json:"config"`
	Enabled   bool               `json:"enabled"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type NotificationRule struct {
	ID          uuid.UUID               `json:"id"`
	ProjectID   uuid.UUID               `json:"project_id"`
	SourceType  NotificationSourceType  `json:"source_type"`
	MinSeverity AlertSeverity           `json:"min_severity"`
	Destination NotificationDestination `json:"destination"`
	Config      []byte                  `json:"config"`
	Enabled     bool                    `json:"enabled"`
	CreatedAt   pgtype.Timestamptz      `json:"created_at"`
}

type PlatformConnection struct {
	ID          uuid.UUID          `json:"id"`
	ProjectID   uuid.UUID          `json:"project_id"`
	Platform    string             `json:"platform"`
	Credentials []byte             `json:"credentials"`
	Enabled     bool               `json:"enabled"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Method      string             `json:"method"`
}

type PostPlatformResult struct {
	ID             uuid.UUID          `json:"id"`
	PostID         uuid.UUID          `json:"post_id"`
	Platform       string             `json:"platform"`
	PlatformPostID string             `json:"platform_post_id"`
	PlatformUrl    string             `json:"platform_url"`
	Success        bool               `json:"success"`
	ErrorMessage   string             `json:"error_message"`
	PublishedAt    pgtype.Timestamptz `json:"published_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Project struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	Settings  []byte             `json:"settings"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type ProjectMember struct {
	ProjectID uuid.UUID          `json:"project_id"`
	UserID    uuid.UUID          `json:"user_id"`
	Role      ProjectRole        `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PublishedPost struct {
	ID          uuid.UUID          `json:"id"`
	ProjectID   uuid.UUID          `json:"project_id"`
	Content     string             `json:"content"`
	Platforms   []string           `json:"platforms"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	Status      PostStatus         `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Title       string             `json:"title"`
	Url         string             `json:"url"`
	PostType    PostType           `json:"post_type"`
}

type ServiceInstance struct {
	ID         uuid.UUID          `json:"id"`
	ProjectID  uuid.UUID          `json:"project_id"`
	Service    ServiceName        `json:"service"`
	ExternalID string             `json:"external_id"`
	Config     []byte             `json:"config"`
	Status     ServiceStatus      `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Name         string             `json:"name"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
