// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: monitor_sources.sql

package storage

import (
	"context"

	"github.com/google/uuid"
)

const createMonitorSource = `-- name: CreateMonitorSource :one
INSERT INTO monitor_sources (project_id, type, config, enabled)
VALUES ($1, $2, $3, $4)
RETURNING id, project_id, type, config, enabled, created_at, updated_at
`

type CreateMonitorSourceParams struct {
	ProjectID uuid.UUID   `json:"project_id"`
	Type      MonitorType `json:"type"`
	Config    []byte      `json:"config"`
	Enabled   bool        `json:"enabled"`
}

func (q *Queries) CreateMonitorSource(ctx context.Context, arg CreateMonitorSourceParams) (MonitorSource, error) {
	row := q.db.QueryRow(ctx, createMonitorSource,
		arg.ProjectID,
		arg.Type,
		arg.Config,
		arg.Enabled,
	)
	var i MonitorSource
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Type,
		&i.Config,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMonitorSource = `-- name: DeleteMonitorSource :exec
DELETE FROM monitor_sources
WHERE id = $1 AND project_id = $2
`

type DeleteMonitorSourceParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) DeleteMonitorSource(ctx context.Context, arg DeleteMonitorSourceParams) error {
	_, err := q.db.Exec(ctx, deleteMonitorSource, arg.ID, arg.ProjectID)
	return err
}

const getMonitorSourceByID = `-- name: GetMonitorSourceByID :one
SELECT id, project_id, type, config, enabled, created_at, updated_at
FROM monitor_sources
WHERE id = $1 AND project_id = $2
`

type GetMonitorSourceByIDParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) GetMonitorSourceByID(ctx context.Context, arg GetMonitorSourceByIDParams) (MonitorSource, error) {
	row := q.db.QueryRow(ctx, getMonitorSourceByID, arg.ID, arg.ProjectID)
	var i MonitorSource
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Type,
		&i.Config,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledMonitorSources = `-- name: ListEnabledMonitorSources :many
SELECT id, project_id, type, config, enabled, created_at, updated_at
FROM monitor_sources
WHERE project_id = $1 AND enabled = true
ORDER BY created_at
`

func (q *Queries) ListEnabledMonitorSources(ctx context.Context, projectID uuid.UUID) ([]MonitorSource, error) {
	rows, err := q.db.Query(ctx, listEnabledMonitorSources, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MonitorSource{}
	for rows.Next() {
		var i MonitorSource
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Type,
			&i.Config,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMonitorSources = `-- name: ListMonitorSources :many
SELECT id, project_id, type, config, enabled, created_at, updated_at
FROM monitor_sources
WHERE project_id = $1
ORDER BY created_at
`

func (q *Queries) ListMonitorSources(ctx context.Context, projectID uuid.UUID) ([]MonitorSource, error) {
	rows, err := q.db.Query(ctx, listMonitorSources, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MonitorSource{}
	for rows.Next() {
		var i MonitorSource
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Type,
			&i.Config,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMonitorSource = `-- name: UpdateMonitorSource :one
UPDATE monitor_sources
SET type = $3, config = $4, enabled = $5
WHERE id = $1 AND project_id = $2
RETURNING id, project_id, type, config, enabled, created_at, updated_at
`

type UpdateMonitorSourceParams struct {
	ID        uuid.UUID   `json:"id"`
	ProjectID uuid.UUID   `json:"project_id"`
	Type      MonitorType `json:"type"`
	Config    []byte      `json:"config"`
	Enabled   bool        `json:"enabled"`
}

func (q *Queries) UpdateMonitorSource(ctx context.Context, arg UpdateMonitorSourceParams) (MonitorSource, error) {
	row := q.db.QueryRow(ctx, updateMonitorSource,
		arg.ID,
		arg.ProjectID,
		arg.Type,
		arg.Config,
		arg.Enabled,
	)
	var i MonitorSource
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Type,
		&i.Config,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
