// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification_rules.sql

package storage

import (
	"context"

	"github.com/google/uuid"
)

const createNotificationRule = `-- name: CreateNotificationRule :one
INSERT INTO notification_rules (project_id, source_type, min_severity, destination, config, enabled)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, source_type, min_severity, destination, config, enabled, created_at
`

type CreateNotificationRuleParams struct {
	ProjectID   uuid.UUID               `json:"project_id"`
	SourceType  NotificationSourceType  `json:"source_type"`
	MinSeverity AlertSeverity           `json:"min_severity"`
	Destination NotificationDestination `json:"destination"`
	Config      []byte                  `json:"config"`
	Enabled     bool                    `json:"enabled"`
}

func (q *Queries) CreateNotificationRule(ctx context.Context, arg CreateNotificationRuleParams) (NotificationRule, error) {
	row := q.db.QueryRow(ctx, createNotificationRule,
		arg.ProjectID,
		arg.SourceType,
		arg.MinSeverity,
		arg.Destination,
		arg.Config,
		arg.Enabled,
	)
	var i NotificationRule
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SourceType,
		&i.MinSeverity,
		&i.Destination,
		&i.Config,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const deleteNotificationRule = `-- name: DeleteNotificationRule :exec
DELETE FROM notification_rules
WHERE id = $1 AND project_id = $2
`

type DeleteNotificationRuleParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) DeleteNotificationRule(ctx context.Context, arg DeleteNotificationRuleParams) error {
	_, err := q.db.Exec(ctx, deleteNotificationRule, arg.ID, arg.ProjectID)
	return err
}

const getNotificationRuleByID = `-- name: GetNotificationRuleByID :one
SELECT id, project_id, source_type, min_severity, destination, config, enabled, created_at
FROM notification_rules
WHERE id = $1 AND project_id = $2
`

type GetNotificationRuleByIDParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) GetNotificationRuleByID(ctx context.Context, arg GetNotificationRuleByIDParams) (NotificationRule, error) {
	row := q.db.QueryRow(ctx, getNotificationRuleByID, arg.ID, arg.ProjectID)
	var i NotificationRule
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SourceType,
		&i.MinSeverity,
		&i.Destination,
		&i.Config,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const listEnabledRulesForProject = `-- name: ListEnabledRulesForProject :many
SELECT id, project_id, source_type, min_severity, destination, config, enabled, created_at
FROM notification_rules
WHERE project_id = $1 AND enabled = true
ORDER BY created_at
`

func (q *Queries) ListEnabledRulesForProject(ctx context.Context, projectID uuid.UUID) ([]NotificationRule, error) {
	rows, err := q.db.Query(ctx, listEnabledRulesForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationRule{}
	for rows.Next() {
		var i NotificationRule
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SourceType,
			&i.MinSeverity,
			&i.Destination,
			&i.Config,
			&i.Enabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationRules = `-- name: ListNotificationRules :many
SELECT id, project_id, source_type, min_severity, destination, config, enabled, created_at
FROM notification_rules
WHERE project_id = $1
ORDER BY created_at
`

func (q *Queries) ListNotificationRules(ctx context.Context, projectID uuid.UUID) ([]NotificationRule, error) {
	rows, err := q.db.Query(ctx, listNotificationRules, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationRule{}
	for rows.Next() {
		var i NotificationRule
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SourceType,
			&i.MinSeverity,
			&i.Destination,
			&i.Config,
			&i.Enabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNotificationRule = `-- name: UpdateNotificationRule :one
UPDATE notification_rules
SET source_type = $3, min_severity = $4, destination = $5, config = $6, enabled = $7
WHERE id = $1 AND project_id = $2
RETURNING id, project_id, source_type, min_severity, destination, config, enabled, created_at
`

type UpdateNotificationRuleParams struct {
	ID          uuid.UUID               `json:"id"`
	ProjectID   uuid.UUID               `json:"project_id"`
	SourceType  NotificationSourceType  `json:"source_type"`
	MinSeverity AlertSeverity           `json:"min_severity"`
	Destination NotificationDestination `json:"destination"`
	Config      []byte                  `json:"config"`
	Enabled     bool                    `json:"enabled"`
}

func (q *Queries) UpdateNotificationRule(ctx context.Context, arg UpdateNotificationRuleParams) (NotificationRule, error) {
	row := q.db.QueryRow(ctx, updateNotificationRule,
		arg.ID,
		arg.ProjectID,
		arg.SourceType,
		arg.MinSeverity,
		arg.Destination,
		arg.Config,
		arg.Enabled,
	)
	var i NotificationRule
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SourceType,
		&i.MinSeverity,
		&i.Destination,
		&i.Config,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}
