// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: platform_connections.sql

package storage

import (
	"context"

	"github.com/google/uuid"
)

const createPlatformConnection = `-- name: CreatePlatformConnection :one
INSERT INTO platform_connections (project_id, platform, credentials, enabled)
VALUES ($1, $2, $3, $4)
RETURNING id, project_id, platform, credentials, enabled, created_at, updated_at
`

type CreatePlatformConnectionParams struct {
	ProjectID   uuid.UUID `json:"project_id"`
	Platform    string    `json:"platform"`
	Credentials []byte    `json:"credentials"`
	Enabled     bool      `json:"enabled"`
}

func (q *Queries) CreatePlatformConnection(ctx context.Context, arg CreatePlatformConnectionParams) (PlatformConnection, error) {
	row := q.db.QueryRow(ctx, createPlatformConnection,
		arg.ProjectID,
		arg.Platform,
		arg.Credentials,
		arg.Enabled,
	)
	var i PlatformConnection
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Platform,
		&i.Credentials,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePlatformConnection = `-- name: DeletePlatformConnection :exec
DELETE FROM platform_connections
WHERE id = $1 AND project_id = $2
`

type DeletePlatformConnectionParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) DeletePlatformConnection(ctx context.Context, arg DeletePlatformConnectionParams) error {
	_, err := q.db.Exec(ctx, deletePlatformConnection, arg.ID, arg.ProjectID)
	return err
}

const getPlatformConnectionByID = `-- name: GetPlatformConnectionByID :one
SELECT id, project_id, platform, credentials, enabled, created_at, updated_at
FROM platform_connections
WHERE id = $1 AND project_id = $2
`

type GetPlatformConnectionByIDParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) GetPlatformConnectionByID(ctx context.Context, arg GetPlatformConnectionByIDParams) (PlatformConnection, error) {
	row := q.db.QueryRow(ctx, getPlatformConnectionByID, arg.ID, arg.ProjectID)
	var i PlatformConnection
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Platform,
		&i.Credentials,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlatformConnectionByPlatform = `-- name: GetPlatformConnectionByPlatform :one
SELECT id, project_id, platform, credentials, enabled, created_at, updated_at
FROM platform_connections
WHERE project_id = $1 AND platform = $2 AND enabled = true
`

type GetPlatformConnectionByPlatformParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Platform  string    `json:"platform"`
}

func (q *Queries) GetPlatformConnectionByPlatform(ctx context.Context, arg GetPlatformConnectionByPlatformParams) (PlatformConnection, error) {
	row := q.db.QueryRow(ctx, getPlatformConnectionByPlatform, arg.ProjectID, arg.Platform)
	var i PlatformConnection
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Platform,
		&i.Credentials,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPlatformConnections = `-- name: ListPlatformConnections :many
SELECT id, project_id, platform, credentials, enabled, created_at, updated_at
FROM platform_connections
WHERE project_id = $1
ORDER BY created_at
`

func (q *Queries) ListPlatformConnections(ctx context.Context, projectID uuid.UUID) ([]PlatformConnection, error) {
	rows, err := q.db.Query(ctx, listPlatformConnections, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformConnection{}
	for rows.Next() {
		var i PlatformConnection
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Platform,
			&i.Credentials,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlatformConnection = `-- name: UpdatePlatformConnection :one
UPDATE platform_connections
SET platform = $3, credentials = $4, enabled = $5
WHERE id = $1 AND project_id = $2
RETURNING id, project_id, platform, credentials, enabled, created_at, updated_at
`

type UpdatePlatformConnectionParams struct {
	ID          uuid.UUID `json:"id"`
	ProjectID   uuid.UUID `json:"project_id"`
	Platform    string    `json:"platform"`
	Credentials []byte    `json:"credentials"`
	Enabled     bool      `json:"enabled"`
}

func (q *Queries) UpdatePlatformConnection(ctx context.Context, arg UpdatePlatformConnectionParams) (PlatformConnection, error) {
	row := q.db.QueryRow(ctx, updatePlatformConnection,
		arg.ID,
		arg.ProjectID,
		arg.Platform,
		arg.Credentials,
		arg.Enabled,
	)
	var i PlatformConnection
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Platform,
		&i.Credentials,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
