// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: processing_rules.sql

package storage

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProcessingRule = `-- name: CreateProcessingRule :one
INSERT INTO processing_rules (project_id, source_id, name, phase, rule_type, config, priority, enabled)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, project_id, source_id, name, phase, rule_type, config, priority, enabled, created_at, updated_at
`

type CreateProcessingRuleParams struct {
	ProjectID uuid.UUID   `json:"project_id"`
	SourceID  pgtype.UUID `json:"source_id"`
	Name      string      `json:"name"`
	Phase     string      `json:"phase"`
	RuleType  string      `json:"rule_type"`
	Config    []byte      `json:"config"`
	Priority  int32       `json:"priority"`
	Enabled   bool        `json:"enabled"`
}

func (q *Queries) CreateProcessingRule(ctx context.Context, arg CreateProcessingRuleParams) (ProcessingRule, error) {
	row := q.db.QueryRow(ctx, createProcessingRule,
		arg.ProjectID,
		arg.SourceID,
		arg.Name,
		arg.Phase,
		arg.RuleType,
		arg.Config,
		arg.Priority,
		arg.Enabled,
	)
	var i ProcessingRule
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SourceID,
		&i.Name,
		&i.Phase,
		&i.RuleType,
		&i.Config,
		&i.Priority,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProcessingRule = `-- name: DeleteProcessingRule :exec
DELETE FROM processing_rules
WHERE id = $1 AND project_id = $2
`

type DeleteProcessingRuleParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) DeleteProcessingRule(ctx context.Context, arg DeleteProcessingRuleParams) error {
	_, err := q.db.Exec(ctx, deleteProcessingRule, arg.ID, arg.ProjectID)
	return err
}

const getProcessingRuleByID = `-- name: GetProcessingRuleByID :one
SELECT id, project_id, source_id, name, phase, rule_type, config, priority, enabled, created_at, updated_at FROM processing_rules
WHERE id = $1 AND project_id = $2
`

type GetProcessingRuleByIDParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) GetProcessingRuleByID(ctx context.Context, arg GetProcessingRuleByIDParams) (ProcessingRule, error) {
	row := q.db.QueryRow(ctx, getProcessingRuleByID, arg.ID, arg.ProjectID)
	var i ProcessingRule
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SourceID,
		&i.Name,
		&i.Phase,
		&i.RuleType,
		&i.Config,
		&i.Priority,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProcessingRules = `-- name: ListProcessingRules :many
SELECT id, project_id, source_id, name, phase, rule_type, config, priority, enabled, created_at, updated_at FROM processing_rules
WHERE project_id = $1
ORDER BY phase, priority, created_at
`

func (q *Queries) ListProcessingRules(ctx context.Context, projectID uuid.UUID) ([]ProcessingRule, error) {
	rows, err := q.db.Query(ctx, listProcessingRules, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProcessingRule{}
	for rows.Next() {
		var i ProcessingRule
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SourceID,
			&i.Name,
			&i.Phase,
			&i.RuleType,
			&i.Config,
			&i.Priority,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRulesForSource = `-- name: ListRulesForSource :many
SELECT id, project_id, source_id, name, phase, rule_type, config, priority, enabled, created_at, updated_at FROM processing_rules
WHERE (source_id = $1 OR source_id IS NULL)
  AND project_id = $2
  AND enabled = true
ORDER BY priority
`

type ListRulesForSourceParams struct {
	SourceID  pgtype.UUID `json:"source_id"`
	ProjectID uuid.UUID   `json:"project_id"`
}

func (q *Queries) ListRulesForSource(ctx context.Context, arg ListRulesForSourceParams) ([]ProcessingRule, error) {
	rows, err := q.db.Query(ctx, listRulesForSource, arg.SourceID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProcessingRule{}
	for rows.Next() {
		var i ProcessingRule
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SourceID,
			&i.Name,
			&i.Phase,
			&i.RuleType,
			&i.Config,
			&i.Priority,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProcessingRule = `-- name: UpdateProcessingRule :one
UPDATE processing_rules
SET source_id = $3, name = $4, phase = $5, rule_type = $6, config = $7, priority = $8, enabled = $9
WHERE id = $1 AND project_id = $2
RETURNING id, project_id, source_id, name, phase, rule_type, config, priority, enabled, created_at, updated_at
`

type UpdateProcessingRuleParams struct {
	ID        uuid.UUID   `json:"id"`
	ProjectID uuid.UUID   `json:"project_id"`
	SourceID  pgtype.UUID `json:"source_id"`
	Name      string      `json:"name"`
	Phase     string      `json:"phase"`
	RuleType  string      `json:"rule_type"`
	Config    []byte      `json:"config"`
	Priority  int32       `json:"priority"`
	Enabled   bool        `json:"enabled"`
}

func (q *Queries) UpdateProcessingRule(ctx context.Context, arg UpdateProcessingRuleParams) (ProcessingRule, error) {
	row := q.db.QueryRow(ctx, updateProcessingRule,
		arg.ID,
		arg.ProjectID,
		arg.SourceID,
		arg.Name,
		arg.Phase,
		arg.RuleType,
		arg.Config,
		arg.Priority,
		arg.Enabled,
	)
	var i ProcessingRule
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SourceID,
		&i.Name,
		&i.Phase,
		&i.RuleType,
		&i.Config,
		&i.Priority,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
