// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package storage

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (name, slug, settings)
VALUES ($1, $2, $3)
RETURNING id, name, slug, settings, created_at, updated_at
`

type CreateProjectParams struct {
	Name     string `json:"name"`
	Slug     string `json:"slug"`
	Settings []byte `json:"settings"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject, arg.Name, arg.Slug, arg.Settings)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProjectMember = `-- name: CreateProjectMember :one
INSERT INTO project_members (project_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING project_id, user_id, role, created_at
`

type CreateProjectMemberParams struct {
	ProjectID uuid.UUID   `json:"project_id"`
	UserID    uuid.UUID   `json:"user_id"`
	Role      ProjectRole `json:"role"`
}

func (q *Queries) CreateProjectMember(ctx context.Context, arg CreateProjectMemberParams) (ProjectMember, error) {
	row := q.db.QueryRow(ctx, createProjectMember, arg.ProjectID, arg.UserID, arg.Role)
	var i ProjectMember
	err := row.Scan(
		&i.ProjectID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects
WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProject, id)
	return err
}

const deleteProjectMember = `-- name: DeleteProjectMember :exec
DELETE FROM project_members
WHERE project_id = $1 AND user_id = $2
`

type DeleteProjectMemberParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteProjectMember(ctx context.Context, arg DeleteProjectMemberParams) error {
	_, err := q.db.Exec(ctx, deleteProjectMember, arg.ProjectID, arg.UserID)
	return err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, name, slug, settings, created_at, updated_at
FROM projects
WHERE id = $1
`

func (q *Queries) GetProjectByID(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectMember = `-- name: GetProjectMember :one
SELECT project_id, user_id, role, created_at
FROM project_members
WHERE project_id = $1 AND user_id = $2
`

type GetProjectMemberParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) GetProjectMember(ctx context.Context, arg GetProjectMemberParams) (ProjectMember, error) {
	row := q.db.QueryRow(ctx, getProjectMember, arg.ProjectID, arg.UserID)
	var i ProjectMember
	err := row.Scan(
		&i.ProjectID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listProjectMembers = `-- name: ListProjectMembers :many
SELECT pm.project_id, pm.user_id, pm.role, pm.created_at,
       u.email AS user_email, u.name AS user_name
FROM project_members pm
JOIN users u ON u.id = pm.user_id
WHERE pm.project_id = $1
ORDER BY pm.created_at
`

type ListProjectMembersRow struct {
	ProjectID uuid.UUID          `json:"project_id"`
	UserID    uuid.UUID          `json:"user_id"`
	Role      ProjectRole        `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UserEmail string             `json:"user_email"`
	UserName  string             `json:"user_name"`
}

func (q *Queries) ListProjectMembers(ctx context.Context, projectID uuid.UUID) ([]ListProjectMembersRow, error) {
	rows, err := q.db.Query(ctx, listProjectMembers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectMembersRow{}
	for rows.Next() {
		var i ListProjectMembersRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.UserEmail,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsForUser = `-- name: ListProjectsForUser :many
SELECT p.id, p.name, p.slug, p.settings, p.created_at, p.updated_at
FROM projects p
JOIN project_members pm ON pm.project_id = p.id
WHERE pm.user_id = $1
ORDER BY p.created_at DESC
`

func (q *Queries) ListProjectsForUser(ctx context.Context, userID uuid.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Settings,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectExistsBySlug = `-- name: ProjectExistsBySlug :one
SELECT EXISTS(SELECT 1 FROM projects WHERE slug = $1)
`

func (q *Queries) ProjectExistsBySlug(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, projectExistsBySlug, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const projectExistsBySlugExcludingID = `-- name: ProjectExistsBySlugExcludingID :one
SELECT EXISTS(SELECT 1 FROM projects WHERE slug = $1 AND id != $2)
`

type ProjectExistsBySlugExcludingIDParams struct {
	Slug string    `json:"slug"`
	ID   uuid.UUID `json:"id"`
}

func (q *Queries) ProjectExistsBySlugExcludingID(ctx context.Context, arg ProjectExistsBySlugExcludingIDParams) (bool, error) {
	row := q.db.QueryRow(ctx, projectExistsBySlugExcludingID, arg.Slug, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name = $2, slug = $3, settings = $4
WHERE id = $1
RETURNING id, name, slug, settings, created_at, updated_at
`

type UpdateProjectParams struct {
	ID       uuid.UUID `json:"id"`
	Name     string    `json:"name"`
	Slug     string    `json:"slug"`
	Settings []byte    `json:"settings"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Settings,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProjectMemberRole = `-- name: UpdateProjectMemberRole :exec
UPDATE project_members
SET role = $3
WHERE project_id = $1 AND user_id = $2
`

type UpdateProjectMemberRoleParams struct {
	ProjectID uuid.UUID   `json:"project_id"`
	UserID    uuid.UUID   `json:"user_id"`
	Role      ProjectRole `json:"role"`
}

func (q *Queries) UpdateProjectMemberRole(ctx context.Context, arg UpdateProjectMemberRoleParams) error {
	_, err := q.db.Exec(ctx, updateProjectMemberRole, arg.ProjectID, arg.UserID, arg.Role)
	return err
}
