// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: published_posts.sql

package storage

import (
	"context"

	"github.com/google/uuid"
)

const countPublishedPosts = `-- name: CountPublishedPosts :one
SELECT count(*) FROM published_posts WHERE project_id = $1
`

func (q *Queries) CountPublishedPosts(ctx context.Context, projectID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPublishedPosts, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPublishedPostsByStatus = `-- name: CountPublishedPostsByStatus :one
SELECT count(*) FROM published_posts WHERE project_id = $1 AND status = $2
`

type CountPublishedPostsByStatusParams struct {
	ProjectID uuid.UUID  `json:"project_id"`
	Status    PostStatus `json:"status"`
}

func (q *Queries) CountPublishedPostsByStatus(ctx context.Context, arg CountPublishedPostsByStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPublishedPostsByStatus, arg.ProjectID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPublishedPost = `-- name: CreatePublishedPost :one
INSERT INTO published_posts (project_id, content, platforms, status)
VALUES ($1, $2, $3, $4)
RETURNING id, project_id, content, platforms, scheduled_at, published_at, status, created_at, updated_at
`

type CreatePublishedPostParams struct {
	ProjectID uuid.UUID  `json:"project_id"`
	Content   string     `json:"content"`
	Platforms []string   `json:"platforms"`
	Status    PostStatus `json:"status"`
}

func (q *Queries) CreatePublishedPost(ctx context.Context, arg CreatePublishedPostParams) (PublishedPost, error) {
	row := q.db.QueryRow(ctx, createPublishedPost,
		arg.ProjectID,
		arg.Content,
		arg.Platforms,
		arg.Status,
	)
	var i PublishedPost
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Content,
		&i.Platforms,
		&i.ScheduledAt,
		&i.PublishedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePublishedPost = `-- name: DeletePublishedPost :exec
DELETE FROM published_posts
WHERE id = $1 AND project_id = $2 AND status = 'draft'
`

type DeletePublishedPostParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) DeletePublishedPost(ctx context.Context, arg DeletePublishedPostParams) error {
	_, err := q.db.Exec(ctx, deletePublishedPost, arg.ID, arg.ProjectID)
	return err
}

const getPublishedPostByID = `-- name: GetPublishedPostByID :one
SELECT id, project_id, content, platforms, scheduled_at, published_at, status, created_at, updated_at
FROM published_posts
WHERE id = $1 AND project_id = $2
`

type GetPublishedPostByIDParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) GetPublishedPostByID(ctx context.Context, arg GetPublishedPostByIDParams) (PublishedPost, error) {
	row := q.db.QueryRow(ctx, getPublishedPostByID, arg.ID, arg.ProjectID)
	var i PublishedPost
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Content,
		&i.Platforms,
		&i.ScheduledAt,
		&i.PublishedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPublishedPosts = `-- name: ListPublishedPosts :many
SELECT id, project_id, content, platforms, scheduled_at, published_at, status, created_at, updated_at
FROM published_posts
WHERE project_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPublishedPostsParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListPublishedPosts(ctx context.Context, arg ListPublishedPostsParams) ([]PublishedPost, error) {
	rows, err := q.db.Query(ctx, listPublishedPosts, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PublishedPost{}
	for rows.Next() {
		var i PublishedPost
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Content,
			&i.Platforms,
			&i.ScheduledAt,
			&i.PublishedAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedPostsByStatus = `-- name: ListPublishedPostsByStatus :many
SELECT id, project_id, content, platforms, scheduled_at, published_at, status, created_at, updated_at
FROM published_posts
WHERE project_id = $1 AND status = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListPublishedPostsByStatusParams struct {
	ProjectID uuid.UUID  `json:"project_id"`
	Status    PostStatus `json:"status"`
	Limit     int32      `json:"limit"`
	Offset    int32      `json:"offset"`
}

func (q *Queries) ListPublishedPostsByStatus(ctx context.Context, arg ListPublishedPostsByStatusParams) ([]PublishedPost, error) {
	rows, err := q.db.Query(ctx, listPublishedPostsByStatus,
		arg.ProjectID,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PublishedPost{}
	for rows.Next() {
		var i PublishedPost
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Content,
			&i.Platforms,
			&i.ScheduledAt,
			&i.PublishedAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPublishedPostPublished = `-- name: SetPublishedPostPublished :one
UPDATE published_posts
SET status = 'published', published_at = now()
WHERE id = $1 AND project_id = $2
RETURNING id, project_id, content, platforms, scheduled_at, published_at, status, created_at, updated_at
`

type SetPublishedPostPublishedParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) SetPublishedPostPublished(ctx context.Context, arg SetPublishedPostPublishedParams) (PublishedPost, error) {
	row := q.db.QueryRow(ctx, setPublishedPostPublished, arg.ID, arg.ProjectID)
	var i PublishedPost
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Content,
		&i.Platforms,
		&i.ScheduledAt,
		&i.PublishedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePublishedPost = `-- name: UpdatePublishedPost :one
UPDATE published_posts
SET content = $3, platforms = $4
WHERE id = $1 AND project_id = $2 AND status = 'draft'
RETURNING id, project_id, content, platforms, scheduled_at, published_at, status, created_at, updated_at
`

type UpdatePublishedPostParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
	Content   string    `json:"content"`
	Platforms []string  `json:"platforms"`
}

func (q *Queries) UpdatePublishedPost(ctx context.Context, arg UpdatePublishedPostParams) (PublishedPost, error) {
	row := q.db.QueryRow(ctx, updatePublishedPost,
		arg.ID,
		arg.ProjectID,
		arg.Content,
		arg.Platforms,
	)
	var i PublishedPost
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Content,
		&i.Platforms,
		&i.ScheduledAt,
		&i.PublishedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePublishedPostStatus = `-- name: UpdatePublishedPostStatus :one
UPDATE published_posts
SET status = $3
WHERE id = $1 AND project_id = $2
RETURNING id, project_id, content, platforms, scheduled_at, published_at, status, created_at, updated_at
`

type UpdatePublishedPostStatusParams struct {
	ID        uuid.UUID  `json:"id"`
	ProjectID uuid.UUID  `json:"project_id"`
	Status    PostStatus `json:"status"`
}

func (q *Queries) UpdatePublishedPostStatus(ctx context.Context, arg UpdatePublishedPostStatusParams) (PublishedPost, error) {
	row := q.db.QueryRow(ctx, updatePublishedPostStatus, arg.ID, arg.ProjectID, arg.Status)
	var i PublishedPost
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Content,
		&i.Platforms,
		&i.ScheduledAt,
		&i.PublishedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
