// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: published_posts.sql

package storage

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countPublishedPosts = `-- name: CountPublishedPosts :one
SELECT count(*) FROM published_posts WHERE project_id = $1
`

func (q *Queries) CountPublishedPosts(ctx context.Context, projectID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPublishedPosts, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPublishedPostsByStatus = `-- name: CountPublishedPostsByStatus :one
SELECT count(*) FROM published_posts WHERE project_id = $1 AND status = $2
`

type CountPublishedPostsByStatusParams struct {
	ProjectID uuid.UUID  `json:"project_id"`
	Status    PostStatus `json:"status"`
}

func (q *Queries) CountPublishedPostsByStatus(ctx context.Context, arg CountPublishedPostsByStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPublishedPostsByStatus, arg.ProjectID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPublishedPost = `-- name: CreatePublishedPost :one
INSERT INTO published_posts (project_id, title, content, url, post_type, platforms, status, reply_to_url)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, project_id, title, content, url, post_type, platforms, reply_to_url, scheduled_at, published_at, status, created_at, updated_at
`

type CreatePublishedPostParams struct {
	ProjectID  uuid.UUID  `json:"project_id"`
	Title      string     `json:"title"`
	Content    string     `json:"content"`
	Url        string     `json:"url"`
	PostType   PostType   `json:"post_type"`
	Platforms  []string   `json:"platforms"`
	Status     PostStatus `json:"status"`
	ReplyToUrl string     `json:"reply_to_url"`
}

type CreatePublishedPostRow struct {
	ID          uuid.UUID          `json:"id"`
	ProjectID   uuid.UUID          `json:"project_id"`
	Title       string             `json:"title"`
	Content     string             `json:"content"`
	Url         string             `json:"url"`
	PostType    PostType           `json:"post_type"`
	Platforms   []string           `json:"platforms"`
	ReplyToUrl  string             `json:"reply_to_url"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	Status      PostStatus         `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreatePublishedPost(ctx context.Context, arg CreatePublishedPostParams) (CreatePublishedPostRow, error) {
	row := q.db.QueryRow(ctx, createPublishedPost,
		arg.ProjectID,
		arg.Title,
		arg.Content,
		arg.Url,
		arg.PostType,
		arg.Platforms,
		arg.Status,
		arg.ReplyToUrl,
	)
	var i CreatePublishedPostRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Content,
		&i.Url,
		&i.PostType,
		&i.Platforms,
		&i.ReplyToUrl,
		&i.ScheduledAt,
		&i.PublishedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePublishedPost = `-- name: DeletePublishedPost :exec
DELETE FROM published_posts
WHERE id = $1 AND project_id = $2 AND status = 'draft'
`

type DeletePublishedPostParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) DeletePublishedPost(ctx context.Context, arg DeletePublishedPostParams) error {
	_, err := q.db.Exec(ctx, deletePublishedPost, arg.ID, arg.ProjectID)
	return err
}

const getPublishedPostByID = `-- name: GetPublishedPostByID :one
SELECT id, project_id, title, content, url, post_type, platforms, reply_to_url, scheduled_at, published_at, status, created_at, updated_at
FROM published_posts
WHERE id = $1 AND project_id = $2
`

type GetPublishedPostByIDParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

type GetPublishedPostByIDRow struct {
	ID          uuid.UUID          `json:"id"`
	ProjectID   uuid.UUID          `json:"project_id"`
	Title       string             `json:"title"`
	Content     string             `json:"content"`
	Url         string             `json:"url"`
	PostType    PostType           `json:"post_type"`
	Platforms   []string           `json:"platforms"`
	ReplyToUrl  string             `json:"reply_to_url"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	Status      PostStatus         `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetPublishedPostByID(ctx context.Context, arg GetPublishedPostByIDParams) (GetPublishedPostByIDRow, error) {
	row := q.db.QueryRow(ctx, getPublishedPostByID, arg.ID, arg.ProjectID)
	var i GetPublishedPostByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Content,
		&i.Url,
		&i.PostType,
		&i.Platforms,
		&i.ReplyToUrl,
		&i.ScheduledAt,
		&i.PublishedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPublishedPosts = `-- name: ListPublishedPosts :many
SELECT id, project_id, title, content, url, post_type, platforms, reply_to_url, scheduled_at, published_at, status, created_at, updated_at
FROM published_posts
WHERE project_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPublishedPostsParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

type ListPublishedPostsRow struct {
	ID          uuid.UUID          `json:"id"`
	ProjectID   uuid.UUID          `json:"project_id"`
	Title       string             `json:"title"`
	Content     string             `json:"content"`
	Url         string             `json:"url"`
	PostType    PostType           `json:"post_type"`
	Platforms   []string           `json:"platforms"`
	ReplyToUrl  string             `json:"reply_to_url"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	Status      PostStatus         `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListPublishedPosts(ctx context.Context, arg ListPublishedPostsParams) ([]ListPublishedPostsRow, error) {
	rows, err := q.db.Query(ctx, listPublishedPosts, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedPostsRow{}
	for rows.Next() {
		var i ListPublishedPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Content,
			&i.Url,
			&i.PostType,
			&i.Platforms,
			&i.ReplyToUrl,
			&i.ScheduledAt,
			&i.PublishedAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedPostsByStatus = `-- name: ListPublishedPostsByStatus :many
SELECT id, project_id, title, content, url, post_type, platforms, reply_to_url, scheduled_at, published_at, status, created_at, updated_at
FROM published_posts
WHERE project_id = $1 AND status = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListPublishedPostsByStatusParams struct {
	ProjectID uuid.UUID  `json:"project_id"`
	Status    PostStatus `json:"status"`
	Limit     int32      `json:"limit"`
	Offset    int32      `json:"offset"`
}

type ListPublishedPostsByStatusRow struct {
	ID          uuid.UUID          `json:"id"`
	ProjectID   uuid.UUID          `json:"project_id"`
	Title       string             `json:"title"`
	Content     string             `json:"content"`
	Url         string             `json:"url"`
	PostType    PostType           `json:"post_type"`
	Platforms   []string           `json:"platforms"`
	ReplyToUrl  string             `json:"reply_to_url"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	Status      PostStatus         `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListPublishedPostsByStatus(ctx context.Context, arg ListPublishedPostsByStatusParams) ([]ListPublishedPostsByStatusRow, error) {
	rows, err := q.db.Query(ctx, listPublishedPostsByStatus,
		arg.ProjectID,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedPostsByStatusRow{}
	for rows.Next() {
		var i ListPublishedPostsByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Content,
			&i.Url,
			&i.PostType,
			&i.Platforms,
			&i.ReplyToUrl,
			&i.ScheduledAt,
			&i.PublishedAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPublishedPostPublished = `-- name: SetPublishedPostPublished :one
UPDATE published_posts
SET status = 'published', published_at = now()
WHERE id = $1 AND project_id = $2
RETURNING id, project_id, title, content, url, post_type, platforms, reply_to_url, scheduled_at, published_at, status, created_at, updated_at
`

type SetPublishedPostPublishedParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

type SetPublishedPostPublishedRow struct {
	ID          uuid.UUID          `json:"id"`
	ProjectID   uuid.UUID          `json:"project_id"`
	Title       string             `json:"title"`
	Content     string             `json:"content"`
	Url         string             `json:"url"`
	PostType    PostType           `json:"post_type"`
	Platforms   []string           `json:"platforms"`
	ReplyToUrl  string             `json:"reply_to_url"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	Status      PostStatus         `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SetPublishedPostPublished(ctx context.Context, arg SetPublishedPostPublishedParams) (SetPublishedPostPublishedRow, error) {
	row := q.db.QueryRow(ctx, setPublishedPostPublished, arg.ID, arg.ProjectID)
	var i SetPublishedPostPublishedRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Content,
		&i.Url,
		&i.PostType,
		&i.Platforms,
		&i.ReplyToUrl,
		&i.ScheduledAt,
		&i.PublishedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePublishedPost = `-- name: UpdatePublishedPost :one
UPDATE published_posts
SET title = $3, content = $4, url = $5, post_type = $6, platforms = $7, reply_to_url = $8
WHERE id = $1 AND project_id = $2 AND status = 'draft'
RETURNING id, project_id, title, content, url, post_type, platforms, reply_to_url, scheduled_at, published_at, status, created_at, updated_at
`

type UpdatePublishedPostParams struct {
	ID         uuid.UUID `json:"id"`
	ProjectID  uuid.UUID `json:"project_id"`
	Title      string    `json:"title"`
	Content    string    `json:"content"`
	Url        string    `json:"url"`
	PostType   PostType  `json:"post_type"`
	Platforms  []string  `json:"platforms"`
	ReplyToUrl string    `json:"reply_to_url"`
}

type UpdatePublishedPostRow struct {
	ID          uuid.UUID          `json:"id"`
	ProjectID   uuid.UUID          `json:"project_id"`
	Title       string             `json:"title"`
	Content     string             `json:"content"`
	Url         string             `json:"url"`
	PostType    PostType           `json:"post_type"`
	Platforms   []string           `json:"platforms"`
	ReplyToUrl  string             `json:"reply_to_url"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	Status      PostStatus         `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdatePublishedPost(ctx context.Context, arg UpdatePublishedPostParams) (UpdatePublishedPostRow, error) {
	row := q.db.QueryRow(ctx, updatePublishedPost,
		arg.ID,
		arg.ProjectID,
		arg.Title,
		arg.Content,
		arg.Url,
		arg.PostType,
		arg.Platforms,
		arg.ReplyToUrl,
	)
	var i UpdatePublishedPostRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Content,
		&i.Url,
		&i.PostType,
		&i.Platforms,
		&i.ReplyToUrl,
		&i.ScheduledAt,
		&i.PublishedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePublishedPostStatus = `-- name: UpdatePublishedPostStatus :one
UPDATE published_posts
SET status = $3
WHERE id = $1 AND project_id = $2
RETURNING id, project_id, title, content, url, post_type, platforms, reply_to_url, scheduled_at, published_at, status, created_at, updated_at
`

type UpdatePublishedPostStatusParams struct {
	ID        uuid.UUID  `json:"id"`
	ProjectID uuid.UUID  `json:"project_id"`
	Status    PostStatus `json:"status"`
}

type UpdatePublishedPostStatusRow struct {
	ID          uuid.UUID          `json:"id"`
	ProjectID   uuid.UUID          `json:"project_id"`
	Title       string             `json:"title"`
	Content     string             `json:"content"`
	Url         string             `json:"url"`
	PostType    PostType           `json:"post_type"`
	Platforms   []string           `json:"platforms"`
	ReplyToUrl  string             `json:"reply_to_url"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	Status      PostStatus         `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdatePublishedPostStatus(ctx context.Context, arg UpdatePublishedPostStatusParams) (UpdatePublishedPostStatusRow, error) {
	row := q.db.QueryRow(ctx, updatePublishedPostStatus, arg.ID, arg.ProjectID, arg.Status)
	var i UpdatePublishedPostStatusRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Content,
		&i.Url,
		&i.PostType,
		&i.Platforms,
		&i.ReplyToUrl,
		&i.ScheduledAt,
		&i.PublishedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
