// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: service_instances.sql

package storage

import (
	"context"

	"github.com/google/uuid"
)

const createServiceInstance = `-- name: CreateServiceInstance :one
INSERT INTO service_instances (project_id, service, external_id, config, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, service, external_id, config, status, created_at, updated_at
`

type CreateServiceInstanceParams struct {
	ProjectID  uuid.UUID     `json:"project_id"`
	Service    ServiceName   `json:"service"`
	ExternalID string        `json:"external_id"`
	Config     []byte        `json:"config"`
	Status     ServiceStatus `json:"status"`
}

func (q *Queries) CreateServiceInstance(ctx context.Context, arg CreateServiceInstanceParams) (ServiceInstance, error) {
	row := q.db.QueryRow(ctx, createServiceInstance,
		arg.ProjectID,
		arg.Service,
		arg.ExternalID,
		arg.Config,
		arg.Status,
	)
	var i ServiceInstance
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Service,
		&i.ExternalID,
		&i.Config,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteServiceInstanceByExternalID = `-- name: DeleteServiceInstanceByExternalID :exec
DELETE FROM service_instances
WHERE project_id = $1 AND service = $2 AND external_id = $3
`

type DeleteServiceInstanceByExternalIDParams struct {
	ProjectID  uuid.UUID   `json:"project_id"`
	Service    ServiceName `json:"service"`
	ExternalID string      `json:"external_id"`
}

func (q *Queries) DeleteServiceInstanceByExternalID(ctx context.Context, arg DeleteServiceInstanceByExternalIDParams) error {
	_, err := q.db.Exec(ctx, deleteServiceInstanceByExternalID, arg.ProjectID, arg.Service, arg.ExternalID)
	return err
}

const getServiceInstanceByExternalID = `-- name: GetServiceInstanceByExternalID :one
SELECT id, project_id, service, external_id, config, status, created_at, updated_at
FROM service_instances
WHERE project_id = $1 AND service = $2 AND external_id = $3
`

type GetServiceInstanceByExternalIDParams struct {
	ProjectID  uuid.UUID   `json:"project_id"`
	Service    ServiceName `json:"service"`
	ExternalID string      `json:"external_id"`
}

func (q *Queries) GetServiceInstanceByExternalID(ctx context.Context, arg GetServiceInstanceByExternalIDParams) (ServiceInstance, error) {
	row := q.db.QueryRow(ctx, getServiceInstanceByExternalID, arg.ProjectID, arg.Service, arg.ExternalID)
	var i ServiceInstance
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Service,
		&i.ExternalID,
		&i.Config,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateServiceInstance = `-- name: UpdateServiceInstance :exec
UPDATE service_instances
SET config = $2, status = $3
WHERE id = $1
`

type UpdateServiceInstanceParams struct {
	ID     uuid.UUID     `json:"id"`
	Config []byte        `json:"config"`
	Status ServiceStatus `json:"status"`
}

func (q *Queries) UpdateServiceInstance(ctx context.Context, arg UpdateServiceInstanceParams) error {
	_, err := q.db.Exec(ctx, updateServiceInstance, arg.ID, arg.Config, arg.Status)
	return err
}
